### PR TITLE
 Reimplemented download function.

### PR DESCRIPTION
**Pull request by rohittp0**
- Cleaned the download function a bit.
- Switched from png to svg. 

Tested on chrome and firefox and everything seems fine. 
Can someone test this in safari to check if it solves #5 and #15?

Live at https://rohittp0.github.io/campus-logo-generator/

### CODE REVIEW

**Comment by rohittp0** [comment]
Forgot to change the fill color when switching themes. Added it.

**Comment by nikiljos** [comment]
But isn't it better to keep the png download option as well, At least non-mac users could get an easily shareable and viewable version

**Comment by rohittp0** [comment]
> But isn't it better to keep the png download option as well, At least non-mac users could get an easily shareable and viewable version

That can also be done. But the logic was it is really easy to convert svg to png and hard to go vice-versa

**Comment by nikiljos** [comment]
> > But isn't it better to keep the png download option as well, At least non-mac users could get an easily shareable and viewable version
> 
> That can also be done. But the logic was it is really easy to convert svg to png and hard to go vice-versa

We could give both the options right?Why not let users choose

**Comment by rohittp0** [comment]
> > > But isn't it better to keep the png download option as well, At least non-mac users could get an easily shareable and viewable version
> > 
> > 
> > That can also be done. But the logic was it is really easy to convert svg to png and hard to go vice-versa
> 
> We could give both the options right?Why not let users choose

Just thought to keep the PR small. Thinking of opening new pull request after this one has been merged.

**Comment by AJAYK-01** [comment]
> * Cleaned the download function a bit.
> * Switched from png to svg.
> 
> Tested on chrome and firefox and everything seems fine.
> Can someone test this in safari to check if it solves #5 and #15?
> 
> Live at https://rohittp0.github.io/campus-logo-generator/

Just checked on Safari and the svg download works fine

**Review by akhilmhdh — APPROVED** [review]
LGTM 👍🏽  Tested in Safari, Mozilla, Chrome

**Pull request merged**
